# This is a basic workflow to help you get started with Actions

name: Greetings

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main","gh-pages" ]
  issues:
    branches: [ "main" ]
    
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for your first pull request"
        pr-message: "Thank you for your first question"
